spring:
  profile: 
    active:
     -dev
---
spring:
  profile: dev #开发环境
  application: 
    name: microservicecloud-config-atguigu-dev
---
spring:
  profile: test #测试环境
  application: 
    name: microservicecloud-config-atguigu-test
  