spring:
  profiles: 
    active:
    - dev
---
server:
  port: 8001
  
spring: 
  profiles: dev #开发环境
  application: 
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDb01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456a?
    dbcp2: 
      min-idle: 5  
      initial-size: 5       
      max-total: 5          
      max-wait-mills: 200  

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath*:mybatis/mapper/**/*.xml

eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true
    

info: 
   app.name: atguigu-microservicecloud
   company.name: www.atguigu.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
--- 
server:
  port: 8001
  
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDb02?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456a?
    dbcp2: 
      min-idle: 5  
      initial-size: 5       
      max-total: 5          
      max-wait-mills: 200  

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath*:mybatis/mapper/**/*.xml

eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true
    

info: 
   app.name: atguigu-microservicecloud
   company.name: www.atguigu.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$
   
